# ftp deploy with Circle CI

version: 2.1

workflows:
  ftp-workflow:
    jobs:
      - build:
          context:
            - polytech
          filters:
            branches:
              only:
                - main
                - master

jobs:
  build:
    docker:
      - image: circleci/node:12.15.0-stretch-browsers
 
    working_directory: ~/repo
 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Install npm
          command: |
            sudo apt-get update
            echo " "
            echo "Building project..."
            npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
      - run: 
          name: Deploy Master Branch
          command: |
            sudo apt-get -qq install git-ftp
            echo " "
            echo "Deploying project..."
            echo $(git status)
            git config git-ftp.syncroot dist
            git ftp push --auto-init --force --user "${FTP_USER}" --passwd "${FTP_PWD}" --syncroot "${FTP_ROOT}/htdocs/client/course1/exam2/"
